image: "rust:latest"

stages:
  - format
  - build
  - test

format:
  stage: format
  script:
    - rustup component add rustfmt --toolchain 1.40.0-x86_64-unknown-linux-gnu
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt -- --check

build:
  stage: build
  script:
    - cargo build --verbose

test:
  stage: test
  script:
    - cargo test --verbose
