name: FmtBuildTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Formatting
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --release --verbose
